CREATE TABLE promotions (
    promo_id INT PRIMARY KEY,
    promo_name VARCHAR(50),
    start_date DATE,
    end_date DATE
);

CREATE TABLE sales (
    sale_id INT PRIMARY KEY,
    sale_date DATE,
    product_name VARCHAR(50),
    quantity INT,
    price_per_unit DECIMAL(10,2),
    promo_id INT
);

-- Promotions Table (10 records)
INSERT INTO promotions (promo_id, promo_name, start_date, end_date) VALUES
(1, 'New Year Mega Sale', '2025-01-01', '2025-01-10'),
(2, 'Republic Day Discounts', '2025-01-20', '2025-01-26'),
(3, 'Valentine Special', '2025-02-10', '2025-02-15'),
(4, 'Summer Bonanza', '2025-04-01', '2025-04-10'),
(5, 'Eid Festive Sale', '2025-04-15', '2025-04-20'),
(6, 'Back to School Offer', '2025-06-01', '2025-06-05'),
(7, 'Independence Day Sale', '2025-08-10', '2025-08-15'),
(8, 'Diwali Dhamaka', '2025-11-01', '2025-11-07'),
(9, 'Christmas Carnival', '2025-12-20', '2025-12-25'),
(10, 'End of Year Clearance', '2025-12-26', '2025-12-31');

-- Sales Table (10 records with some promotions missing)
INSERT INTO sales (sale_id, sale_date, product_name, quantity, price_per_unit, promo_id) VALUES
(1, '2025-01-02', 'LED TV', 5, 30000, 1),
(2, '2025-01-03', 'Washing Machine', 2, 20000, 1),
(3, '2025-01-21', 'Refrigerator', 1, 25000, 2),
(4, '2025-02-12', 'Perfume Set', 10, 1500, 3),
(5, '2025-04-02', 'Air Conditioner', 3, 35000, 4),
(6, '2025-04-16', 'Smartphone', 15, 15000, 5),
(7, '2025-08-12', 'Microwave Oven', 4, 8000, 7),
(8, '2025-11-03', 'Gold Necklace', 2, 50000, 8),
(9, '2025-12-22', 'Christmas Cake', 20, 1200, 9),
(10, '2025-12-28', 'Sofa Set', 1, 45000, 10);


/*  Business Scenario
You work for a retail supermarket chain.
Management wants to know all promotions planned in the marketing calendar — and the total revenue generated by 
each promotion (even if the promotion didn’t result in any sales).

They specifically want:
Promotion Name
Promotion Start & End Date
Total Sales Revenue linked to that promotion (0 if no sales were recorded)
Sorted by promotion start date*/

